Refactor delete functionality using Ajax
dren-haziri/Jobsway2goMvc pull request #119
Opened 2023-02-14 02:11 UTC by agnesa23

![image](https://user-images.githubusercontent.com/79428415/218620889-8cf02469-0001-488d-9787-b54d491c1251.png)

2023-02-14 08:09 UTC, dren-haziri requested changes

2023-02-14 08:09 UTC, dren-haziri commented on Jobsway2goMvc/wwwroot/js/confirm-modal.js
> +    }
change position to top right

2023-02-14 08:09 UTC, dren-haziri commented on Jobsway2goMvc/Views/Collections/Index.cshtml
> +
delete comments

2023-02-14 08:09 UTC, dren-haziri commented on Jobsway2goMvc/Views/Collections/Index.cshtml
> +    //});
delete comments

2023-02-14 08:09 UTC, dren-haziri commented on Jobsway2goMvc/Controllers/JobCategoriesController.cs
> -        public async Task<IActionResult> DeleteConfirmed(int id)
return anti forgery token attribute back

2023-02-14 08:09 UTC, dren-haziri commented on Jobsway2goMvc/Controllers/GroupsController.cs
> +        public async Task<IActionResult> DeleteConfirmed([FromRoute] int id)
return attributes back

2023-02-14 08:09 UTC, dren-haziri commented on Jobsway2goMvc/Controllers/CollectionsController.cs
> +        [HttpPost]
return attributes back

2023-02-14 23:28 UTC, agnesa23 commented on Jobsway2goMvc/wwwroot/js/confirm-modal.js
> +    }
done

2023-02-14 23:28 UTC, agnesa23 commented on Jobsway2goMvc/Views/Collections/Index.cshtml
> +
deleted

2023-02-14 23:29 UTC, agnesa23 commented on Jobsway2goMvc/Controllers/GroupsController.cs
> +        public async Task<IActionResult> DeleteConfirmed([FromRoute] int id)
added attribute back

2023-02-15 08:04 UTC, dren-haziri requested changes

2023-02-15 08:04 UTC, dren-haziri commented on Jobsway2goMvc/Views/Collections/Index.cshtml
> -</script>
Was this intended to be deleted?

2023-02-15 08:56 UTC, dren-haziri approved these changes

2023-02-15 13:01 UTC, merged